Setup

In [11]:
import toolbox_morph
import numpy as np
import matplotlib.pyplot as plt
from astropy.table import Table
import glob

In [12]:
path_main_directory = '/home/wolbach/Desktop/SRMP/morph_project/'
path_SFH_table = path_main_directory + 'SFH/Behroozi+19/'

Grid

In [13]:
# make grid

alpha_test_values_list = np.linspace(0.0, 10.0, num=11)
beta_test_values_list = np.linspace(0.0, 3.0, num=7)
gamma_test_values_list = np.linspace(-3.0, 3.0, num=7)
delta_test_values_list = np.linspace(-3.0, 3.0, num=7)

print(alpha_test_values_list)
print(beta_test_values_list)
print(gamma_test_values_list)
print(delta_test_values_list)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[-3. -2. -1.  0.  1.  2.  3.]
[-3. -2. -1.  0.  1.  2.  3.]


In [14]:
radius_kpc = np.linspace(0.0, 20.0, num=201)
print (radius_kpc)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

Observations

In [15]:
def Mosleh2013_SF(mass):
    alpha, beta, gamma, M0 = 0.109, 0.263, 10**-0.743, 10**10.204
    return(gamma*mass**alpha*(1+mass/M0)**(beta-alpha))

def Mosleh2013_Q(mass):
    alpha, beta, gamma, M0 = 0.014, 0.912, 10**-0.058, 10**10.555
    return(gamma*mass**alpha*(1+mass/M0)**(beta-alpha))

In [16]:
# test lists
alpha_test_values_list = [0.3, 1.0, 3.0]
beta_test_values_list = [0.7 ,0.8, 0.9]
gamma_test_values_list = [-0.3, -0.4, -0.5]
delta_test_values_list = [0.4, 0.5, 0.3]

Functions

In [17]:
def compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list):    
    
    RM_Q_list = []
    RM_SF_list = []

    for ii_alpha in alpha_test_values_list:
        for ii_beta in beta_test_values_list:
            for ii_gamma in gamma_test_values_list:
                for ii_delta in delta_test_values_list:
                    gal_Q = toolbox_morph.galaxy(radius_kpc, SFH_table['scale_factor'], SFH_table['SFH_Q'], [ii_alpha,ii_beta,ii_gamma,ii_delta])
                    RM_Q_list.append(gal_Q.get_size(redshift_in=0.0))
                    gal_SF = toolbox_morph.galaxy(radius_kpc, SFH_table['scale_factor'], SFH_table['SFH_SF'], [ii_alpha,ii_beta,ii_gamma,ii_delta])
                    RM_SF_list.append(gal_SF.get_size(redshift_in=0.0))

    mass_Q = gal_Q.get_mass_after_mass_loss(redshift_in=0.0)
    mass_SF = gal_SF.get_mass_after_mass_loss(redshift_in=0.0)
    
    return(mass_Q, mass_SF, RM_Q_list, RM_SF_list)

Sample grid

In [19]:
# create list of SFH tables
list_SFH_tables = glob.glob(path_SFH_table + '*a1.002310.dat')
print(list_SFH_tables)

['/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.70_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm8.70_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.50_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.10_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.50_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.50_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.70_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.30_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm8.50_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.70_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.30_a1.002310.dat', '/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/s

In [20]:
mass_Q_list = []
mass_SF_list = []
RM_Q_stack = []
RM_SF_stack = []
index = 0;

# for each SFH table, mass_Q, mass_SF, and RM_Q_list, RM_SF_list are found and added to lists initialized above
for SFH_file in list_SFH_tables:
    print('reading in', SFH_file)
    SFH_table = Table.read(SFH_file, format='ascii', names=('scale_factor', 'SFH_all', 'SFH_all_up', 'SFH_all_dw', 'SFH_SF', 'SFH_SF_up', 'SFH_SF_dw', 'SFH_Q', 'SFH_Q_up', 'SFH_Q_dw', 'SFH_Cen', 'SFH_Cen_up', 'SFH_Cen_dw', 'SFH_Sat', 'SFH_Sat_up', 'SFH_Sat_dw', 'scale_factor_begin', 'scale_factor_end')) 
    mass_Q, mass_SF, RM_Q_list, RM_SF_list = compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list)
   
    mass_Q_list.append(mass_Q)
    mass_SF_list.append(mass_SF)
    if (index == 0):
        RM_Q_stack.append(RM_Q_list)
        RM_SF_stack.append(RM_SF_list)
    else:
        np.vstack(RM_Q_list, RM_Q_stack)
        np.vstack(RM_SF_list, RM_SF_stack)

reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.70_a1.002310.dat


/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:74: RuntimeWarning: divide by zero encountered in true_divide
  self.time_boundary = cosmo.age(1.0/self.scale_factor_boundary-1.0).value
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:75: RuntimeWarning: divide by zero encountered in true_divide
  self.time_dt = np.diff(cosmo.age(1.0/self.scale_factor_boundary-1.0).value)
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:79: RuntimeWarning: invalid value encountered in true_divide
  self.Rs = self.Rs_params[0]*(self.mass/10**10)**self.Rs_params[1]*((self.SFR/self.mass)/10**-10)**self.Rs_params[2]*(1+self.redshift)**self.Rs_params[3]


reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm8.70_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.50_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.10_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.50_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.50_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.70_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.30_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm8.50_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.70_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.30_a1.002310.dat
reading in /home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+

In [21]:
#speed improvement, develop algorithm to find best fit values from lists

In [22]:
mass_Q_list

[5557078847.293091,
 548974020.4607923,
 331636430706.02783,
 1382029762.3264863,
 37766974077.55003,
 3492580511.2501893,
 61983875553.43999,
 2198671491.445731,
 346998176.4934355,
 509662998799.09247,
 23278791785.17418,
 8889686000.115383,
 869051127.4947574,
 148632336692.79898,
 219330765497.23145,
 98240850893.31345,
 14282175708.813581]

In [23]:
RM_Q_stack

[[nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 [nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan

In [24]:
variable = 0 
for idx in range(len(mass_Q_list)):
    if np.isnan(RM_Q_stack[idx][0]) | np.isnan(RM_SF_stack[idx][0]):
        continue
    else:
        variable = variable + (np.log10(Mosleh2013_Q(mass_Q_list[idx]))-np.log10(RM_Q_stack[idx]))**2 + (np.log10(Mosleh2013_SF(mass_SF_list[idx]))-np.log10(RM_SF_stack[idx]))**2
    
idx_min_comb = np.sqrt(variable).argmin() 
print (idx_min_comb)

30


In [25]:
variable

array([1.49246261, 1.24392573, 1.76730777, 1.9395031 , 1.65083572,
       2.25521812, 2.4626968 , 2.13643502, 2.81495595, 1.02242185,
       0.83968092, 1.23052109, 1.37775153, 1.15455756, 1.62474045,
       1.80696149, 1.5455512 , 2.09200636, 0.6948729 , 0.56699988,
       0.84546181, 0.96469396, 0.79951252, 1.15196808, 1.30718288,
       1.10389988, 1.52984657, 0.11026516, 0.15439132, 0.0821541 ,
       0.07301148, 0.08572852, 0.07880714, 0.10204587, 0.07857996,
       0.14599418, 0.17039326, 0.22774829, 0.1251612 , 0.09523364,
       0.12740117, 0.07757793, 0.0765981 , 0.07885015, 0.09086143,
       0.23385238, 0.29713777, 0.17974692, 0.13511111, 0.17828804,
       0.10320344, 0.08403699, 0.1028327 , 0.07844918, 1.01065133,
       1.12159646, 0.90137456, 0.78577366, 0.89245756, 0.68290976,
       0.57664625, 0.67432767, 0.48519403, 1.02684719, 1.12768236,
       0.9272057 , 0.81607162, 0.91395261, 0.72097884, 0.6174948 ,
       0.70878128, 0.53083449, 1.01655359, 1.10737477, 0.92671

In [26]:
alpha_list = []
beta_list = []
gamma_list = []
delta_list = []
    
for ii_alpha in alpha_test_values_list:
        for ii_beta in beta_test_values_list:
            for ii_gamma in gamma_test_values_list:
                for ii_delta in delta_test_values_list:
                    alpha_list.append(ii_alpha)
                    beta_list.append(ii_beta)
                    gamma_list.append(ii_gamma)
                    delta_list.append(ii_delta)

In [27]:
print (alpha_list[idx_min_comb])
print (beta_list[idx_min_comb])
print (gamma_list[idx_min_comb])
print (delta_list[idx_min_comb])

1.0
0.7
-0.4
0.4


Debugging test

In [40]:
SFH_file = "/home/wolbach/Desktop/SRMP/morph_project/SFH/Behroozi+19/sfh_sm9.70_a1.002310.dat"

SFH_table = Table.read(SFH_file, format='ascii', names=('scale_factor', 'SFH_all', 'SFH_all_up', 'SFH_all_dw', 'SFH_SF', 'SFH_SF_up', 'SFH_SF_dw', 'SFH_Q', 'SFH_Q_up', 'SFH_Q_dw', 'SFH_Cen', 'SFH_Cen_up', 'SFH_Cen_dw', 'SFH_Sat', 'SFH_Sat_up', 'SFH_Sat_dw', 'scale_factor_begin', 'scale_factor_end')) 
mass_Q, mass_SF, RM_Q_list, RM_SF_list = compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list)
print (RM_Q_list)

/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:74: RuntimeWarning: divide by zero encountered in true_divide
  self.time_boundary = cosmo.age(1.0/self.scale_factor_boundary-1.0).value
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:75: RuntimeWarning: divide by zero encountered in true_divide
  self.time_dt = np.diff(cosmo.age(1.0/self.scale_factor_boundary-1.0).value)
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:79: RuntimeWarning: invalid value encountered in true_divide
  self.Rs = self.Rs_params[0]*(self.mass/10**10)**self.Rs_params[1]*((self.SFR/self.mass)/10**-10)**self.Rs_params[2]*(1+self.redshift)**self.Rs_params[3]


[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [41]:
# problem in getSize command in toolbox

In [43]:
  for ii_alpha in alpha_test_values_list:
        for ii_beta in beta_test_values_list:
            for ii_gamma in gamma_test_values_list:
                for ii_delta in delta_test_values_list:
                    gal_Q = toolbox_morph.galaxy(radius_kpc, SFH_table['scale_factor'], SFH_table['SFH_Q'], [ii_alpha,ii_beta,ii_gamma,ii_delta])
                    print (gal_Q.get_size(redshift_in=0.0))

/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:74: RuntimeWarning: divide by zero encountered in true_divide
  self.time_boundary = cosmo.age(1.0/self.scale_factor_boundary-1.0).value
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:75: RuntimeWarning: divide by zero encountered in true_divide
  self.time_dt = np.diff(cosmo.age(1.0/self.scale_factor_boundary-1.0).value)
/home/wolbach/Desktop/SRMP/morph_project/morph_tools/toolbox_morph.py:79: RuntimeWarning: invalid value encountered in true_divide
  self.Rs = self.Rs_params[0]*(self.mass/10**10)**self.Rs_params[1]*((self.SFR/self.mass)/10**-10)**self.Rs_params[2]*(1+self.redshift)**self.Rs_params[3]


nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
