# Setup

In [1]:
import toolbox_morph
import numpy as np
import matplotlib.pyplot as plt
from astropy.table import Table
import glob

In [2]:
path_main_directory = '/Users/sandrotacchella/ASTRO/SRMP/morph_project/'
path_SFH_table = path_main_directory + 'SFH/Behroozi+19/'

# Grid

In [14]:
# make grid

alpha_test_values_list = np.logspace(-1, 1.0, num=11)
beta_test_values_list = np.linspace(0.0, 3.0, num=7)
gamma_test_values_list = np.linspace(-3.0, 3.0, num=7)
delta_test_values_list = np.linspace(-3.0, 3.0, num=7)

print(alpha_test_values_list)
print(beta_test_values_list)
print(gamma_test_values_list)
print(delta_test_values_list)


[ 0.1         0.15848932  0.25118864  0.39810717  0.63095734  1.
  1.58489319  2.51188643  3.98107171  6.30957344 10.        ]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[-3. -2. -1.  0.  1.  2.  3.]
[-3. -2. -1.  0.  1.  2.  3.]


In [3]:
alpha_test_values_list = np.logspace(-1, 1.0, num=2)
beta_test_values_list = np.linspace(0.0, 3.0, num=2)
gamma_test_values_list = np.linspace(-3.0, 3.0, num=2)
delta_test_values_list = np.linspace(-3.0, 3.0, num=2)

print(alpha_test_values_list)
print(beta_test_values_list)
print(gamma_test_values_list)
print(delta_test_values_list)


[ 0.1 10. ]
[0. 3.]
[-3.  3.]
[-3.  3.]


In [4]:
radius_kpc = np.linspace(0.0, 20.0, num=201)
print radius_kpc


[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

# Observations

In [5]:
def Mosleh2013_SF(mass):
    alpha, beta, gamma, M0 = 0.109, 0.263, 10**-0.743, 10**10.204
    return(gamma*mass**alpha*(1+mass/M0)**(beta-alpha))

def Mosleh2013_Q(mass):
    alpha, beta, gamma, M0 = 0.014, 0.912, 10**-0.058, 10**10.555
    return(gamma*mass**alpha*(1+mass/M0)**(beta-alpha))


# Functions

In [14]:
def compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list):    
    
    RM_Q_list = []
    RM_SF_list = []

    for ii_alpha in alpha_test_values_list:
        for ii_beta in beta_test_values_list:
            for ii_gamma in gamma_test_values_list:
                for ii_delta in delta_test_values_list:
                    gal_Q = toolbox_morph.galaxy(radius_kpc, SFH_table['scale_factor'], SFH_table['SFH_Q'], [ii_alpha,ii_beta,ii_gamma,ii_delta])
                    RM_Q_list.append(gal_Q.get_size(redshift_in=0.0))
                    gal_SF = toolbox_morph.galaxy(radius_kpc, SFH_table['scale_factor'], SFH_table['SFH_SF'], [ii_alpha,ii_beta,ii_gamma,ii_delta])
                    RM_SF_list.append(gal_SF.get_size(redshift_in=0.0))

    mass_Q = gal_Q.get_mass_after_mass_loss(redshift_in=0.0)
    mass_SF = gal_SF.get_mass_after_mass_loss(redshift_in=0.0)
    
    return(mass_Q, mass_SF, RM_Q_list, RM_SF_list)


# Sample Grid


In [7]:
# create list of SFH tables
list_SFH_tables = glob.glob(path_SFH_table + '*a1.002310.dat')
print(list_SFH_tables)

['/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.10_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.30_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.50_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.70_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.90_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.10_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.30_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.50_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm11.70_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm8.50_a1.002310.dat', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_s

In [13]:
mass_Q_list = []
mass_SF_list = []
RM_Q_stack = []
RM_SF_stack = []
index = 0;

# for each SFH table, mass_Q, mass_SF, and RM_Q_list, RM_SF_list are found and added to lists initialized above
for SFH_file in list_SFH_tables:
    print('reading in', SFH_file)
    SFH_table = Table.read(SFH_file, format='ascii', names=('scale_factor', 'SFH_all', 'SFH_all_up', 'SFH_all_dw', 'SFH_SF', 'SFH_SF_up', 'SFH_SF_dw', 'SFH_Q', 'SFH_Q_up', 'SFH_Q_dw', 'SFH_Cen', 'SFH_Cen_up', 'SFH_Cen_dw', 'SFH_Sat', 'SFH_Sat_up', 'SFH_Sat_dw', 'scale_factor_begin', 'scale_factor_end')) 
    mass_Q, mass_SF, RM_Q_list, RM_SF_list = compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list)
   
    mass_Q_list.append(mass_Q)
    mass_SF_list.append(mass_SF)
    if (index == 0):
        RM_Q_stack.append(RM_Q_list)
        RM_SF_stack.append(RM_SF_list)
    else:
        np.vstack(RM_Q_list, RM_Q_stack)
        np.vstack(RM_SF_list, RM_SF_stack)
    

('reading in', '/Users/sandrotacchella/ASTRO/SRMP/morph_project/SFH/Behroozi+19/sfh_sm10.10_a1.002310.dat')
0.1 0.0 -3.0 -3.0
[9.88885987e-12 2.06435024e-11 1.24371346e-12 4.20397009e-13
 6.92022961e-13 7.65361541e-13 2.41959787e-12 2.72437024e-12
 5.68117421e-12 7.53934884e-12 1.13900564e-11 2.09550887e-11
 2.40164883e-11 3.66120557e-11 5.94414085e-11 9.13199739e-11
 1.39038357e-10 2.08711163e-10 3.06191855e-10 4.50294947e-10
 6.34285653e-10 8.49241739e-10 1.26865824e-09 1.70748097e-09
 2.14018221e-09 2.76891761e-09 3.57503775e-09 4.74256319e-09
 6.61429637e-09 9.05314402e-09 1.17681256e-08 1.61305478e-08
 2.27460921e-08 3.07639500e-08 4.28613444e-08 5.66401036e-08
 7.02081751e-08 8.89567458e-08 1.08756053e-07 1.33597041e-07
 1.74622021e-07 2.26736637e-07 2.98181907e-07 3.85929958e-07
 4.63073224e-07 5.43905988e-07 6.54404368e-07 8.04737149e-07
 1.01024078e-06 1.22835488e-06 1.46472324e-06 1.75290799e-06
 2.01623434e-06 2.42700294e-06 2.87912651e-06 3.36930750e-06
 3.86438444e-06 4.36

In [8]:
SFH_file = list_SFH_tables[-1]
SFH_table = Table.read(SFH_file, format='ascii', names=('scale_factor', 'SFH_all', 'SFH_all_up', 'SFH_all_dw', 'SFH_SF', 'SFH_SF_up', 'SFH_SF_dw', 'SFH_Q', 'SFH_Q_up', 'SFH_Q_dw', 'SFH_Cen', 'SFH_Cen_up', 'SFH_Cen_dw', 'SFH_Sat', 'SFH_Sat_up', 'SFH_Sat_dw', 'scale_factor_begin', 'scale_factor_end')) 
print SFH_table['SFH_Q']
mass_Q, mass_SF, RM_Q_list, RM_SF_list = compute_sizes(SFH_table, alpha_test_values_list, beta_test_values_list, gamma_test_values_list, delta_test_values_list)
print mass_Q, mass_SF, RM_Q_list, RM_SF_list



   SFH_Q   
-----------
        0.0
1.45711e-05
6.52086e-05
0.000186593
 0.00040069
0.000911379
 0.00170814
 0.00354743
 0.00494372
 0.00783907
        ...
   0.290845
   0.265206
   0.239618
   0.221605
   0.201592
   0.177532
   0.159238
   0.132632
   0.105831
  0.0696946
  0.0222453
Length = 178 rows
0.1 0.0 -3.0 -3.0


/Users/sandrotacchella/ASTRO/SRMP/morph_project/morph_tools/toolbox_morph.py:77: RuntimeWarning: divide by zero encountered in divide
  self.time_boundary = cosmo.age(1.0/self.scale_factor_boundary-1.0).value
/Users/sandrotacchella/ASTRO/SRMP/morph_project/morph_tools/toolbox_morph.py:78: RuntimeWarning: divide by zero encountered in divide
  self.time_dt = np.diff(cosmo.age(1.0/self.scale_factor_boundary-1.0).value)
/Users/sandrotacchella/ASTRO/SRMP/morph_project/morph_tools/toolbox_morph.py:82: RuntimeWarning: invalid value encountered in divide
  self.Rs = self.Rs_params[0]*(self.mass/10**10)**self.Rs_params[1]*((self.SFR/self.mass)/10**-10)**self.Rs_params[2]*(1+self.redshift)**self.Rs_params[3]


[0.00000000e+00 2.06388289e-11 1.38800944e-12 6.10727277e-13
 6.74122691e-13 7.05615056e-13 1.01959308e-12 1.12661997e-12
 2.37966282e-12 3.09862091e-12 5.94811444e-12 1.33830379e-11
 1.41129137e-11 2.42887729e-11 4.95120332e-11 7.96272209e-11
 1.36550679e-10 1.94872817e-10 2.74958578e-10 4.04105614e-10
 5.93966784e-10 8.65738319e-10 1.20345008e-09 1.69927704e-09
 2.34504636e-09 2.97003368e-09 3.66426636e-09 5.08436024e-09
 6.65214012e-09 9.41732810e-09 1.35631878e-08 1.91982654e-08
 2.55750000e-08 3.38296162e-08 4.57181876e-08 5.83057605e-08
 7.53998930e-08 1.00016524e-07 1.28257928e-07 1.64855608e-07
 2.06493593e-07 2.57809708e-07 3.23972390e-07 3.94604414e-07
 4.75319265e-07 5.66787593e-07 7.18844602e-07 9.00282683e-07
 1.08738513e-06 1.30581023e-06 1.47487053e-06 1.74288868e-06
 2.11069319e-06 2.55674583e-06 2.95452070e-06 3.53465549e-06
 4.11482398e-06 4.63996123e-06 5.32279608e-06 6.03987599e-06
 6.77965636e-06 7.83504823e-06 9.13071983e-06 1.01730181e-05
 1.15544522e-05 1.317237

In [15]:
print mass_Q, mass_SF, RM_Q_list, RM_SF_list


8889686000.115383 8210234948.652673 [0.3456126471838967, 0.27303659659332613, 0.8964157368572792, 2.4725578498225826, 0.45624816061482126, 0.4690846280691096, 0.23644340780373366, 3.873311917786729, 0.45755488125094307, 2.5973183441229386, 4.581655893971803, 3.6834470522240315, 0.7098396367230877, 0.9736343663315248, 4.9057107918374, 4.913078361946242] [0.3106494694184493, 0.3120488422606736, 1.1272169412272726, 1.818070436531535, 0.4724732764361966, 0.5178277905349427, 0.20949672476578468, 1.7619630154413424, 0.5352693864263096, 2.0025504248010235, 5.170950271069265, 5.259681676870327, 0.8545887625705628, 0.8348809895635978, 6.058392776082586, 8.448075736151406]


In [11]:

def make_SFR_profile(radius, SFR_total, Rs):
    '''
    This function returns the SFR surface density profile,
    which we assume to be an exponential disk.
    Input:
        radius    : in kpc
        SFR_total : total SFR (in Msun/yr)
        Rs        : scale radius (in kpc)
    Output:
        SFRD      : SFR surface density (in Msun/yr/kpc^2)
    '''
    normalization = SFR_total/(2.0*np.pi*Rs**2)
    return(normalization*np.exp(-1.0*radius/Rs))



In [12]:
make_SFR_profile(radius_kpc, 0.0, 1.0)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#speed improvement, develop algorithm to find best fit values from lists

In [10]:
mass_Q_list

[14282175708.81358,
 23278791785.17418,
 37766974077.550026,
 61983875553.43999,
 98240850893.31345,
 148632336692.79898,
 219330765497.23145,
 331636430706.02783,
 509662998799.09247,
 346998176.4934355,
 548974020.4607923,
 869051127.4947573,
 1382029762.3264863,
 2198671491.445731,
 3492580511.25019,
 5557078847.293091,
 8889686000.115383]

In [17]:
RM_Q_stack

[[0.4067906811343732,
  0.2852555763901732,
  0.9671455410512265,
  2.7299770020229506,
  0.5841793443319977,
  0.510522588088765,
  0.718503939823562,
  6.065080118201831,
  0.4171841265426039,
  2.4081939786159348,
  3.8680975027987117,
  3.1553624470895962,
  0.745472055115233,
  1.4958403264754838,
  4.416438638535072,
  4.68356064665937],
 [0.4864948666268987,
  0.27463259651188804,
  0.9870365830424809,
  2.949631545510035,
  0.5142709770372009,
  0.6393139347590028,
  2.446595011901824,
  3.4181798167422546,
  0.3945266921040302,
  2.329314578694065,
  3.7031929386058966,
  2.536318446562851,
  0.8945553465199036,
  2.3205911783545163,
  4.640495927225414,
  4.805302187862038],
 [0.5182171138123918,
  0.26011043389917765,
  1.0336460763387378,
  3.042589711065305,
  0.5536328051673031,
  1.0159063872898313,
  4.732006435802405,
  2.5880784328995166,
  0.4026510799411682,
  2.139919889490265,
  4.09932854824114,
  2.179101759961527,
  1.0965030548299697,
  2.81179650086255,
  5.3

In [12]:
variable = 0 
for idx in range(len(mass_Q_list)):
    if np.isnan(RM_Q_stack[idx][0]) | np.isnan(RM_SF_stack[idx][0]):
        continue
    else:
        variable = variable + (np.log10(Mosleh2013_Q(mass_Q_list[idx]))-np.log10(RM_Q_stack[idx]))**2 + (np.log10(Mosleh2013_SF(mass_SF_list[idx]))-np.log10(RM_SF_stack[idx]))**2
    
idx_min_comb = np.sqrt(variable).argmin() 
print (idx_min_comb)

0


In [13]:
variable

0

In [14]:
alpha_list = []
beta_list = []
gamma_list = []
delta_list = []
    
for ii_alpha in alpha_test_values_list:
        for ii_beta in beta_test_values_list:
            for ii_gamma in gamma_test_values_list:
                for ii_delta in delta_test_values_list:
                    alpha_list.append(ii_alpha)
                    beta_list.append(ii_beta)
                    gamma_list.append(ii_gamma)
                    delta_list.append(ii_delta)

In [15]:
print (alpha_list[idx_min_comb])
print (beta_list[idx_min_comb])
print (gamma_list[idx_min_comb])
print (delta_list[idx_min_comb])

0.0
0.0
-3.0
-3.0
